twig:
    file_name_pattern: '*.twig'
    form_themes: ["bootstrap_5_layout.html.twig"]
    globals:
        addUser: '@App\Repository\AdRepository'

when@test:
    twig:
        strict_variables: true
