vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
       products:
           uri_prefix: /images/ads
           upload_destination: '%kernel.project_dir%/public/images/ads'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
           delete_on_update: true
           delete_on_remove: true
